# Generated by Django 5.2.17 on 2026-09-24 19:34

import django.db.models.deletion
import students.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True, verbose_name='عنوان سال تحصیلی')),
                ('slug', models.SlugField(max_length=32, unique=True, verbose_name='شناسه')),
                ('is_active', models.BooleanField(default=False, verbose_name='سال فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'سال تحصیلی',
                'verbose_name_plural': 'سال\u200cهای تحصیلی',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True, verbose_name='کد پایه')),
                ('name_fa', models.CharField(max_length=80, verbose_name='نام پایه')),
                ('stage', models.CharField(choices=[('preschool', 'پیش\u200cدبستان'), ('elementary_first', 'دبستان دوره اول'), ('elementary_second', 'دبستان دوره دوم'), ('middle_first', 'متوسطه دوره اول')], max_length=32, verbose_name='مقطع')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'پایه تحصیلی',
                'verbose_name_plural': 'پایه\u200cهای تحصیلی',
                'ordering': ['sort_order', 'name_fa'],
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام کلاس')),
                ('capacity', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='ظرفیت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='students.academicyear', verbose_name='سال تحصیلی')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='students.gradelevel', verbose_name='پایه')),
            ],
            options={
                'verbose_name': 'کلاس',
                'verbose_name_plural': 'کلاس\u200cها',
                'ordering': ['academic_year__title', 'grade__sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_code', models.CharField(max_length=10, unique=True, validators=[students.validators.validate_national_code], verbose_name='کد ملی')),
                ('first_name', models.CharField(max_length=80, verbose_name='نام')),
                ('last_name', models.CharField(max_length=120, verbose_name='نام خانوادگی')),
                ('father_name', models.CharField(blank=True, max_length=120, verbose_name='نام پدر')),
                ('gender', models.CharField(choices=[('female', 'دختر'), ('male', 'پسر'), ('unspecified', 'ثبت نشده')], default='female', max_length=16, verbose_name='جنسیت')),
                ('birth_date_jalali', models.CharField(blank=True, max_length=16, verbose_name='تاریخ تولد شمسی')),
                ('primary_mobile', models.CharField(blank=True, max_length=11, validators=[students.validators.validate_mobile], verbose_name='موبایل اصلی')),
                ('sms_mobile', models.CharField(blank=True, max_length=11, validators=[students.validators.validate_mobile], verbose_name='شماره پیامک')),
                ('sms_mobile_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تأیید شماره پیامک')),
                ('home_phone', models.CharField(blank=True, max_length=32, verbose_name='تلفن منزل')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='کد پستی')),
                ('address', models.TextField(blank=True, verbose_name='نشانی')),
                ('portal_enabled', models.BooleanField(default=False, verbose_name='دسترسی پرتال')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='اطلاعات تکمیلی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'دانش\u200cآموز',
                'verbose_name_plural': 'دانش\u200cآموزان',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='SmsDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(default='login_otp', max_length=32)),
                ('destination_masked', models.CharField(max_length=32)),
                ('provider', models.CharField(blank=True, max_length=80)),
                ('provider_message_id', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('queued', 'در صف'), ('sent', 'ارسال\u200cشده'), ('failed', 'ناموفق')], default='queued', max_length=16)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_deliveries', to='students.student')),
            ],
            options={
                'verbose_name': 'ارسال پیامک',
                'verbose_name_plural': 'ارسال\u200cهای پیامک',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OtpChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11)),
                ('code_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('request_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_challenges', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuardianContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('father', 'پدر'), ('mother', 'مادر'), ('other', 'سایر')], max_length=16, verbose_name='نسبت')),
                ('full_name', models.CharField(blank=True, max_length=160, verbose_name='نام و نام خانوادگی')),
                ('national_code', models.CharField(blank=True, max_length=10, verbose_name='کد ملی')),
                ('mobile', models.CharField(blank=True, max_length=11, validators=[students.validators.validate_mobile], verbose_name='موبایل')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('can_receive_sms', models.BooleanField(default=True, verbose_name='دریافت پیامک')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='اطلاعات تکمیلی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='students.student')),
            ],
            options={
                'verbose_name': 'اطلاعات ولی',
                'verbose_name_plural': 'اطلاعات اولیا',
                'ordering': ['student_id', 'relation'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال'), ('transferred', 'انتقالی'), ('graduated', 'فارغ\u200cالتحصیل')], default='active', max_length=16, verbose_name='وضعیت')),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('source_row', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='students.academicyear', verbose_name='سال تحصیلی')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='students.classroom', verbose_name='کلاس')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='students.gradelevel', verbose_name='پایه')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='students.student', verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'ثبت\u200cنام',
                'verbose_name_plural': 'ثبت\u200cنام\u200cها',
                'ordering': ['-academic_year__title', 'grade__sort_order', 'classroom__name', 'student__last_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checksum', models.CharField(db_index=True, max_length=64)),
                ('filenames', models.JSONField(default=list)),
                ('report', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('committed', 'ثبت\u200cشده'), ('failed', 'ناموفق')], default='committed', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to='students.academicyear')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'واردسازی دانش\u200cآموزان',
                'verbose_name_plural': 'واردسازی\u200cهای دانش\u200cآموزان',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.UniqueConstraint(fields=('academic_year', 'grade', 'name'), name='unique_classroom_per_year_grade'),
        ),
        migrations.AddIndex(
            model_name='otpchallenge',
            index=models.Index(fields=['student', '-created_at'], name='student_otp_recent_idx'),
        ),
        migrations.AddConstraint(
            model_name='guardiancontact',
            constraint=models.UniqueConstraint(fields=('student', 'relation'), name='unique_guardian_relation_per_student'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'academic_year'), name='unique_student_enrollment_per_year'),
        ),
    ]
