# Generated by Django 5.2.17 on 2026-08-18 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=200, verbose_name='نام فارسی')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='نام انگلیسی')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description_fa', models.TextField(blank=True, verbose_name='توضیحات فارسی')),
                ('description_en', models.TextField(blank=True, verbose_name='توضیحات انگلیسی')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='نام آیکن Lucide')),
                ('image', models.ImageField(blank=True, null=True, upload_to='working-groups/', verbose_name='تصویر')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'کارگروه',
                'verbose_name_plural': 'کارگروه\u200cها',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkingGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=200, verbose_name='نام فارسی')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='نام انگلیسی')),
                ('role_fa', models.CharField(blank=True, max_length=200, verbose_name='سمت فارسی')),
                ('role_en', models.CharField(blank=True, max_length=200, verbose_name='سمت انگلیسی')),
                ('summary_fa', models.TextField(blank=True, verbose_name='خلاصه فارسی')),
                ('summary_en', models.TextField(blank=True, verbose_name='خلاصه انگلیسی')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='working-group-members/', verbose_name='تصویر')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='content.workinggroup', verbose_name='کارگروه')),
            ],
            options={
                'verbose_name': 'عضو کارگروه',
                'verbose_name_plural': 'اعضای کارگروه',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
