# Generated by Django 5.2.17 on 2026-08-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=300, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='عنوان انگلیسی')),
                ('summary_fa', models.TextField(blank=True, verbose_name='خلاصه فارسی')),
                ('summary_en', models.TextField(blank=True, verbose_name='خلاصه انگلیسی')),
                ('body_fa', models.TextField(blank=True, verbose_name='متن فارسی')),
                ('body_en', models.TextField(blank=True, verbose_name='متن انگلیسی')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='articles/%Y/%m/', verbose_name='تصویر شاخص')),
                ('category', models.CharField(choices=[('education', 'آموزش'), ('parenting', 'فرزندپروری'), ('pedagogy', 'روش\u200cهای آموزشی'), ('psychology', 'روان\u200cشناسی'), ('general', 'عمومی')], default='general', max_length=30, verbose_name='دسته\u200cبندی')),
                ('tags', models.JSONField(blank=True, default=list, help_text="مثال: ['آموزش', 'دانش\u200cآموز', 'مدرسه']", verbose_name='برچسب\u200cها')),
                ('author_name', models.CharField(blank=True, max_length=200, verbose_name='نام نویسنده')),
                ('reading_time_min', models.PositiveIntegerField(default=5, verbose_name='زمان مطالعه به دقیقه')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending_review', 'در انتظار بررسی'), ('approved', 'تأیید شده'), ('published', 'منتشر شده'), ('archived', 'آرشیو شده')], default='draft', max_length=30, verbose_name='وضعیت')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('slug_fa', models.SlugField(allow_unicode=True, blank=True, max_length=300, verbose_name='Slug فارسی')),
                ('slug_en', models.SlugField(blank=True, max_length=300, verbose_name='Slug انگلیسی')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مقاله ویژه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-publish_date', '-id'],
            },
        ),
    ]
