# Generated by Django 5.2.17 on 2026-08-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_fa', models.CharField(max_length=300, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(blank=True, max_length=300, verbose_name='عنوان انگلیسی')),
                ('description_fa', models.TextField(blank=True, verbose_name='توضیحات فارسی')),
                ('description_en', models.TextField(blank=True, verbose_name='توضیحات انگلیسی')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='events/%Y/%m/', verbose_name='تصویر رویداد')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='دسته\u200cبندی')),
                ('event_date', models.DateTimeField(verbose_name='تاریخ و ساعت رویداد')),
                ('venue_fa', models.CharField(blank=True, max_length=300, verbose_name='محل برگزاری فارسی')),
                ('venue_en', models.CharField(blank=True, max_length=300, verbose_name='محل برگزاری انگلیسی')),
                ('organizer_fa', models.CharField(blank=True, max_length=300, verbose_name='برگزارکننده فارسی')),
                ('organizer_en', models.CharField(blank=True, max_length=300, verbose_name='برگزارکننده انگلیسی')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='ظرفیت')),
                ('registration_deadline', models.DateTimeField(blank=True, null=True, verbose_name='مهلت ثبت\u200cنام')),
                ('registration_url', models.URLField(blank=True, verbose_name='لینک ثبت\u200cنام')),
                ('map_url', models.URLField(blank=True, verbose_name='لینک نقشه')),
                ('status', models.CharField(choices=[('upcoming', 'در پیش\u200cرو'), ('completed', 'برگزار شده')], default='upcoming', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'رویداد',
                'verbose_name_plural': 'رویدادها',
                'ordering': ['event_date'],
            },
        ),
    ]
