# Generated by Django 5.2.17 on 2026-08-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero-slides/%Y/%m/', verbose_name='تصویر اسلاید')),
                ('alt_fa', models.CharField(blank=True, max_length=250, verbose_name='متن جایگزین فارسی')),
                ('alt_en', models.CharField(blank=True, max_length=250, verbose_name='متن جایگزین انگلیسی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'اسلاید صفحه اصلی',
                'verbose_name_plural': 'اسلایدهای صفحه اصلی',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
