# Generated by Django 5.2.17 on 2026-08-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_heroslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=30, verbose_name='شماره تماس')),
                ('expertise_area', models.CharField(max_length=200, verbose_name='حوزه تخصص')),
                ('resume', models.FileField(blank=True, null=True, upload_to='collaboration-resumes/%Y/%m/', verbose_name='رزومه')),
                ('message', models.TextField(verbose_name='پیام')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('reviewing', 'در حال بررسی'), ('contacted', 'تماس گرفته شده'), ('accepted', 'پذیرفته شده'), ('rejected', 'رد شده')], default='new', max_length=20, verbose_name='وضعیت')),
                ('admin_notes', models.TextField(blank=True, verbose_name='یادداشت مدیریت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'درخواست همکاری',
                'verbose_name_plural': 'درخواست\u200cهای همکاری',
                'ordering': ['-created_at'],
            },
        ),
    ]
