# Generated by Django 5.2 on 2026-09-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_collaborationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinggroup',
            name='objectives_en',
            field=models.TextField(blank=True, verbose_name='اهداف انگلیسی'),
        ),
        migrations.AddField(
            model_name='workinggroup',
            name='objectives_fa',
            field=models.TextField(blank=True, verbose_name='اهداف فارسی'),
        ),
        migrations.AddField(
            model_name='workinggroup',
            name='programs_en',
            field=models.TextField(blank=True, verbose_name='برنامه‌ها و فعالیت‌ها انگلیسی'),
        ),
        migrations.AddField(
            model_name='workinggroup',
            name='programs_fa',
            field=models.TextField(blank=True, verbose_name='برنامه‌ها و فعالیت‌ها فارسی'),
        ),
        migrations.AddField(
            model_name='workinggroup',
            name='summary_en',
            field=models.TextField(blank=True, verbose_name='خلاصه معرفی انگلیسی'),
        ),
        migrations.AddField(
            model_name='workinggroup',
            name='summary_fa',
            field=models.TextField(blank=True, verbose_name='خلاصه معرفی فارسی'),
        ),
        migrations.AddField(
            model_name='workinggroupmember',
            name='bio_en',
            field=models.TextField(blank=True, verbose_name='درباره عضو انگلیسی'),
        ),
        migrations.AddField(
            model_name='workinggroupmember',
            name='bio_fa',
            field=models.TextField(blank=True, verbose_name='درباره عضو فارسی'),
        ),
        migrations.AddField(
            model_name='workinggroupmember',
            name='education_en',
            field=models.TextField(blank=True, verbose_name='تحصیلات انگلیسی'),
        ),
        migrations.AddField(
            model_name='workinggroupmember',
            name='education_fa',
            field=models.TextField(blank=True, verbose_name='تحصیلات فارسی'),
        ),
        migrations.AddField(
            model_name='workinggroupmember',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='ایمیل کاری'),
        ),
        migrations.AddField(
            model_name='workinggroupmember',
            name='experience_en',
            field=models.TextField(blank=True, verbose_name='سوابق شغلی انگلیسی'),
        ),
        migrations.AddField(
            model_name='workinggroupmember',
            name='experience_fa',
            field=models.TextField(blank=True, verbose_name='سوابق شغلی فارسی'),
        ),
        migrations.AddField(
            model_name='workinggroupmember',
            name='expertise_en',
            field=models.TextField(blank=True, verbose_name='تخصص‌ها انگلیسی'),
        ),
        migrations.AddField(
            model_name='workinggroupmember',
            name='expertise_fa',
            field=models.TextField(blank=True, verbose_name='تخصص‌ها فارسی'),
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('title_fa', models.CharField(max_length=200, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='عنوان انگلیسی')),
                ('description_fa', models.TextField(blank=True, verbose_name='توضیحات فارسی')),
                ('description_en', models.TextField(blank=True, verbose_name='توضیحات انگلیسی')),
                ('age_label_fa', models.CharField(blank=True, max_length=100, verbose_name='بازه سنی/پایه فارسی')),
                ('age_label_en', models.CharField(blank=True, max_length=100, verbose_name='بازه سنی/پایه انگلیسی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='education-levels/', verbose_name='تصویر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مقطع تحصیلی',
                'verbose_name_plural': 'مقاطع تحصیلی',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=200, verbose_name='نام فارسی')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='نام انگلیسی')),
                ('description_fa', models.TextField(blank=True, verbose_name='توضیحات فارسی')),
                ('description_en', models.TextField(blank=True, verbose_name='توضیحات انگلیسی')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='نام آیکن Lucide')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'امکانات فضای آموزشی',
                'verbose_name_plural': 'امکانات فضای آموزشی',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fa', models.CharField(max_length=250, verbose_name='نام فارسی')),
                ('name_en', models.CharField(blank=True, max_length=250, verbose_name='نام انگلیسی')),
                ('url', models.URLField(blank=True, verbose_name='نشانی وب‌سایت')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='نام آیکن Lucide')),
                ('image', models.ImageField(blank=True, null=True, upload_to='partners/', verbose_name='لوگو')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مؤسسه همکار',
                'verbose_name_plural': 'مؤسسه‌های همکار',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('home_gallery', 'گالری صفحه اصلی'), ('educational_space', 'فضای آموزشی')], max_length=40, verbose_name='بخش سایت')),
                ('image', models.ImageField(upload_to='site-images/%Y/%m/', verbose_name='تصویر')),
                ('alt_fa', models.CharField(blank=True, max_length=250, verbose_name='متن جایگزین فارسی')),
                ('alt_en', models.CharField(blank=True, max_length=250, verbose_name='متن جایگزین انگلیسی')),
                ('caption_fa', models.CharField(blank=True, max_length=300, verbose_name='شرح فارسی')),
                ('caption_en', models.CharField(blank=True, max_length=300, verbose_name='شرح انگلیسی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تصویر سایت',
                'verbose_name_plural': 'تصاویر سایت',
                'ordering': ['section', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True, verbose_name='کلید بخش')),
                ('title_fa', models.CharField(blank=True, max_length=250, verbose_name='عنوان فارسی')),
                ('title_en', models.CharField(blank=True, max_length=250, verbose_name='عنوان انگلیسی')),
                ('subtitle_fa', models.TextField(blank=True, verbose_name='زیرعنوان فارسی')),
                ('subtitle_en', models.TextField(blank=True, verbose_name='زیرعنوان انگلیسی')),
                ('body_fa', models.TextField(blank=True, verbose_name='متن فارسی')),
                ('body_en', models.TextField(blank=True, verbose_name='متن انگلیسی')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'متن بخش سایت',
                'verbose_name_plural': 'متن بخش‌های سایت',
                'ordering': ['key'],
            },
        ),
    ]
