# Generated by Django 5.2 on 2026-09-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_editable_site_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='thumbnail_image',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='news-thumbnails/%Y/%m/',
                verbose_name='تصویر بندانگشتی',
            ),
        ),
        migrations.AddField(
            model_name='article',
            name='thumbnail_image',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='article-thumbnails/%Y/%m/',
                verbose_name='تصویر بندانگشتی',
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='thumbnail_image',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='event-thumbnails/%Y/%m/',
                verbose_name='تصویر بندانگشتی رویداد',
            ),
        ),
    ]
