# Generated by Django 5.2.17 on 2026-09-24 20:37

import django.core.validators
import django.db.models.deletion
import students.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0002_seed_school_structure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=64, unique=True, verbose_name='کد درس')),
                ('name_fa', models.CharField(max_length=120, verbose_name='نام فارسی')),
                ('name_en', models.CharField(blank=True, max_length=120, verbose_name='نام انگلیسی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'درس\u200cها',
                'ordering': ['sort_order', 'name_fa'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel_code', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='کد پرسنلی')),
                ('first_name', models.CharField(max_length=80, verbose_name='نام')),
                ('last_name', models.CharField(max_length=120, verbose_name='نام خانوادگی')),
                ('mobile', models.CharField(blank=True, max_length=11, validators=[students.validators.validate_mobile], verbose_name='موبایل')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('bio', models.TextField(blank=True, verbose_name='معرفی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'معلم',
                'verbose_name_plural': 'معلمان',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to='students.academicyear', verbose_name='سال تحصیلی')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to='students.classroom', verbose_name='کلاس')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to='learning.subject', verbose_name='درس')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to='learning.teacher', verbose_name='معلم')),
            ],
            options={
                'verbose_name': 'تخصیص تدریس',
                'verbose_name_plural': 'تخصیص\u200cهای تدریس',
                'ordering': ['-academic_year__title', 'classroom__grade__sort_order', 'classroom__name', 'subject__sort_order'],
            },
        ),
        migrations.CreateModel(
            name='OnlineSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='عنوان جلسه')),
                ('starts_at', models.DateTimeField(verbose_name='زمان شروع')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(480)], verbose_name='مدت جلسه')),
                ('join_window_minutes', models.PositiveSmallIntegerField(default=15, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)], verbose_name='زمان مجاز ورود پیش از شروع')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('scheduled', 'برنامه\u200cریزی\u200cشده'), ('live', 'در حال برگزاری'), ('ended', 'پایان\u200cیافته'), ('cancelled', 'لغوشده')], default='draft', max_length=16, verbose_name='وضعیت')),
                ('allow_recording', models.BooleanField(default=True, verbose_name='ضبط جلسه')),
                ('provider_key', models.CharField(default='unconfigured', editable=False, max_length=40)),
                ('external_meeting_id', models.CharField(blank=True, editable=False, max_length=180)),
                ('provider_metadata', models.JSONField(blank=True, default=dict, editable=False)),
                ('recording_url', models.URLField(blank=True, verbose_name='لینک ضبط')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_online_sessions', to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='online_sessions', to='learning.teachingassignment', verbose_name='کلاس و درس')),
            ],
            options={
                'verbose_name': 'جلسه آنلاین',
                'verbose_name_plural': 'جلسات آنلاین',
                'ordering': ['-starts_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('expected', 'در فهرست'), ('present', 'حاضر'), ('absent', 'غایب'), ('excused', 'غیبت موجه')], default='expected', max_length=16, verbose_name='وضعیت حضور')),
                ('first_joined_at', models.DateTimeField(blank=True, null=True)),
                ('last_left_at', models.DateTimeField(blank=True, null=True)),
                ('attended_seconds', models.PositiveIntegerField(default=0)),
                ('provider_participant_id', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='learning.onlinesession', verbose_name='جلسه')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='online_attendance_records', to='students.student', verbose_name='دانش\u200cآموز')),
            ],
            options={
                'verbose_name': 'حضور در جلسه',
                'verbose_name_plural': 'حضور و غیاب جلسات',
                'ordering': ['session__starts_at', 'student__last_name'],
                'constraints': [models.UniqueConstraint(fields=('session', 'student'), name='unique_student_session_attendance')],
            },
        ),
        migrations.AddConstraint(
            model_name='teachingassignment',
            constraint=models.UniqueConstraint(fields=('academic_year', 'classroom', 'subject', 'teacher'), name='unique_teacher_subject_class_year'),
        ),
        migrations.AddConstraint(
            model_name='onlinesession',
            constraint=models.UniqueConstraint(fields=('assignment', 'starts_at'), name='unique_assignment_session_start'),
        ),
    ]
